project_id = "yknmcddrfkggphrktivd"

[functions.contact-organizer]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.support-form-email]
verify_jwt = false

[functions.support-request]
verify_jwt = false

[functions.test-deploy]
verify_jwt = false

[functions.generate-og-image]
verify_jwt = false

[functions.alerts]
verify_jwt = false

[functions.alerts-verify]
verify_jwt = false

[functions.alerts-manage]
verify_jwt = false

[functions.alerts-digest]
verify_jwt = false

[functions.alerts-unsubscribe]
verify_jwt = false

[functions.alerts-instant]
verify_jwt = false

[functions.sitemap-tournaments]
verify_jwt = false

[functions.sitemap-index]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.fix-tournament-coordinates]
verify_jwt = false

[functions.fix-venue-coordinates]
verify_jwt = false

[functions.geocode-exact-addresses]
verify_jwt = false

[functions.fix-location-pins]
verify_jwt = false

[functions.blog-like]
verify_jwt = false

[functions.blog-sitemap]
verify_jwt = false

[functions.blog-feed]
verify_jwt = false