project_id = "yknmcddrfkggphrktivd"

[functions.auth-emails]
verify_jwt = false

[functions.contact-organizer]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.support-form-email]
verify_jwt = false

[functions.support-request]
verify_jwt = false

[functions.test-deploy]
verify_jwt = false

[functions.generate-og-image]
verify_jwt = false